### ISSUE TITLE
파일 순서가 불편하네요 ㅡㅡ

### ISSUE THREAD

**Issue by qlido** [JobMarketIsCold/JavaScriptIsCold#10]
1
17
18
19
2
3
4

너무 킹받습니다 자릿수를 맞추어 주세요~~
01
02
03
04
17
18
19

**Comment by HUN1i** [comment]
손님 패드렸습니다^^

**Comment by HUN1i** [comment]
아니 해드렸습니다^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
